#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# source dbconfig-common stuff
dbc_dbtypes="mysql, pgsql"
dbc_dbuser="snort"
dbc_dbname="snort"

if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
    . /usr/share/dbconfig-common/dpkg/config
    dbc_go acidbase $@
fi

db_input medium "acidbase/webserver"        || true
db_text high    "acidbase/base_advisory"    || true
db_go

