#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/frontend.config ]; then
	# source dbconfig-common stuff
	dbc_dbtypes="mysql, pgsql"
	dbc_dbuser="snort"
	dbc_dbname="snort"

    . /usr/share/dbconfig-common/dpkg/frontend.config
    dbc_go acidbase $@
fi

db_input medium "acidbase/webserver"        || true
db_text high    "acidbase/base_advisory"    || true
db_go

